# Generated by Django 6.0.7 on 2026-08-05 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('contractor', 'مقاول'), ('supervisor', 'مراقب')], default='contractor', max_length=20, verbose_name='نوع المستخدم'),
        ),
    ]
