# Generated by Django 6.0.7 on 2026-08-06 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_role'),
        ('locations', '0002_alter_locationtype_options_alter_unit_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profiles', to='locations.unit', verbose_name='وحدة التنسيق'),
        ),
    ]
