# Generated by Django 6.0.7 on 2026-08-02 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300, verbose_name='نص الملاحظة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'ملاحظة',
                'verbose_name_plural': 'الملاحظات',
                'ordering': ['text'],
            },
        ),
        migrations.CreateModel(
            name='NoteLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.location', verbose_name='الموقع')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.note', verbose_name='الملاحظة')),
            ],
            options={
                'verbose_name': 'ملاحظة موقع',
                'verbose_name_plural': 'ملاحظات المواقع',
                'unique_together': {('note', 'location')},
            },
        ),
        migrations.AddField(
            model_name='note',
            name='locations',
            field=models.ManyToManyField(blank=True, related_name='notes', through='notes.NoteLocation', to='locations.location', verbose_name='المواقع المرتبطة'),
        ),
    ]
