# Generated by Django 6.0.7 on 2026-08-06 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_worktype'),
    ]

    operations = [
        migrations.AddField(
            model_name='worktype',
            name='category',
            field=models.CharField(choices=[('all', 'عام / مشترك'), ('restroom', 'دورات المياه'), ('open_space', 'مساحات انتشارية ومواقع')], default='all', max_length=20, verbose_name='الفئة المستهدفة'),
        ),
    ]
