# Generated by Django 6.0.7 on 2026-08-06 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_worktype_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkItemDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='اسم البند التفصيلي')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('work_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='notes.worktype', verbose_name='نوع العمل')),
            ],
            options={
                'verbose_name': 'بند تفصيلي',
                'verbose_name_plural': 'البنود التفصيلية',
                'ordering': ['work_type', 'name'],
            },
        ),
    ]
