# Generated by Django 6.0.7 on 2026-08-06 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_workitemdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worktype',
            name='category',
            field=models.CharField(choices=[('restroom', 'دورات المياه'), ('location', 'مواقع'), ('open_space', 'مساحات انتشارية')], default='location', max_length=20, verbose_name='تصنيف الموقع'),
        ),
    ]
