# Generated by Django 6.0.7 on 2026-08-06 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_alter_worktype_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workitemdetail',
            options={'ordering': ['work_type', 'name'], 'verbose_name': 'عنصر', 'verbose_name_plural': 'العناصر'},
        ),
        migrations.AlterField(
            model_name='workitemdetail',
            name='name',
            field=models.CharField(max_length=250, verbose_name='اسم العنصر'),
        ),
        migrations.CreateModel(
            name='WorkActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='اسم النشاط')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='notes.workitemdetail', verbose_name='العنصر')),
            ],
            options={
                'verbose_name': 'نشاط',
                'verbose_name_plural': 'الأنشطة',
                'ordering': ['element', 'name'],
            },
        ),
    ]
