# Generated by Django 6.0.7 on 2026-08-06 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_alter_workitemdetail_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worktype',
            name='name',
            field=models.CharField(max_length=200, verbose_name='نوع العمل'),
        ),
        migrations.AlterUniqueTogether(
            name='worktype',
            unique_together={('name', 'category')},
        ),
    ]
