# Generated by Django 6.0.7 on 2026-08-02 05:57

import django.db.models.deletion
import reports.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('notes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_number', models.CharField(editable=False, max_length=30, unique=True, verbose_name='رقم التقرير')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('idempotency_key', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='مفتاح التفرد')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='locations.location', verbose_name='الموقع')),
                ('location_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='locations.locationtype', verbose_name='نوع الموقع')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='locations.unit', verbose_name='الوحدة')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'تقرير',
                'verbose_name_plural': 'التقارير',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_items', to='notes.note', verbose_name='الملاحظة')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='reports.report', verbose_name='التقرير')),
            ],
            options={
                'verbose_name': 'عنصر تقرير',
                'verbose_name_plural': 'عناصر التقارير',
                'unique_together': {('report', 'note')},
            },
        ),
        migrations.CreateModel(
            name='ReportItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=reports.models.report_image_path, verbose_name='الصورة')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع')),
                ('report_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='reports.reportitem', verbose_name='عنصر التقرير')),
            ],
            options={
                'verbose_name': 'صورة',
                'verbose_name_plural': 'الصور',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
