# Generated by Django 6.0.7 on 2026-08-02 06:43

import django.db.models.deletion
import reports.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_worktype'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='خط العرض'),
        ),
        migrations.AddField(
            model_name='report',
            name='location_photo',
            field=models.ImageField(blank=True, null=True, upload_to=reports.models.location_photo_path, verbose_name='صورة تحديد الموقع'),
        ),
        migrations.AddField(
            model_name='report',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='خط الطول'),
        ),
        migrations.AddField(
            model_name='reportitem',
            name='work_classification',
            field=models.CharField(blank=True, max_length=300, verbose_name='تصنيف العمل'),
        ),
        migrations.AddField(
            model_name='reportitem',
            name='work_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_items', to='notes.worktype', verbose_name='نوع العمل'),
        ),
    ]
