# Generated by Django 6.0.7 on 2026-08-02 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_worktype'),
        ('reports', '0002_report_latitude_report_location_photo_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reportitem',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='reportitem',
            name='note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_items', to='notes.note', verbose_name='الملاحظة'),
        ),
    ]
