# Generated by Django 6.0.7 on 2026-08-06 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_workitemdetail'),
        ('reports', '0003_alter_reportitem_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportitem',
            name='work_item_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_items', to='notes.workitemdetail', verbose_name='البند التفصيلي'),
        ),
    ]
