# Generated by Django 6.0.7 on 2026-08-06 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_alter_locationtype_options_alter_unit_options_and_more'),
        ('reports', '0004_reportitem_work_item_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='locations.location', verbose_name='اسم الموقع'),
        ),
        migrations.AlterField(
            model_name='report',
            name='location_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='locations.locationtype', verbose_name='تصنيف الموقع'),
        ),
        migrations.AlterField(
            model_name='report',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='locations.unit', verbose_name='وحدة التنسيق'),
        ),
    ]
