# Generated by Django 6.0.7 on 2026-08-06 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_alter_workitemdetail_options_and_more'),
        ('reports', '0005_alter_report_location_alter_report_location_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportitem',
            name='work_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_items', to='notes.workactivity', verbose_name='النشاط'),
        ),
        migrations.AlterField(
            model_name='reportitem',
            name='work_item_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_items', to='notes.workitemdetail', verbose_name='العنصر'),
        ),
    ]
