# Generated by Django 6.0.7 on 2026-08-06 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locationtype',
            options={'ordering': ['name'], 'verbose_name': 'تصنيف موقع', 'verbose_name_plural': 'تصنيفات المواقع'},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['name'], 'verbose_name': 'وحدة تنسيق', 'verbose_name_plural': 'وحدات التنسيق'},
        ),
        migrations.AlterField(
            model_name='location',
            name='location_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='locations.locationtype', verbose_name='تصنيف الموقع'),
        ),
        migrations.AlterField(
            model_name='location',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='locations.unit', verbose_name='وحدة التنسيق'),
        ),
        migrations.AlterField(
            model_name='locationtype',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='تصنيف الموقع'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='اسم وحدة التنسيق'),
        ),
    ]
